#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskManager.Resource", IsApplication=true)]

namespace TaskManager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06002d
			public const int AliceBlue = 2131099693;
			
			// aapt resource value: 0x7f06000a
			public const int AntiqueWhite = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int AntiqueWhite2 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int AntiqueWhite3 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int AntiqueWhite4 = 2131099661;
			
			// aapt resource value: 0x7f060053
			public const int Aquamarine = 2131099731;
			
			// aapt resource value: 0x7f06002c
			public const int Azure = 2131099692;
			
			// aapt resource value: 0x7f060074
			public const int Beige = 2131099764;
			
			// aapt resource value: 0x7f060010
			public const int Bisque = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int Bisque2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int Bisque3 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int Bisque4 = 2131099667;
			
			// aapt resource value: 0x7f060032
			public const int Black = 2131099698;
			
			// aapt resource value: 0x7f06000f
			public const int BlanchedAlmond = 2131099663;
			
			// aapt resource value: 0x7f060042
			public const int Blue = 2131099714;
			
			// aapt resource value: 0x7f060093
			public const int BlueViolet = 2131099795;
			
			// aapt resource value: 0x7f06007a
			public const int Brown = 2131099770;
			
			// aapt resource value: 0x7f060073
			public const int Burlywood = 2131099763;
			
			// aapt resource value: 0x7f060051
			public const int CadetBlue = 2131099729;
			
			// aapt resource value: 0x7f06005d
			public const int Chartreuse = 2131099741;
			
			// aapt resource value: 0x7f060078
			public const int Chocolate = 2131099768;
			
			// aapt resource value: 0x7f060080
			public const int Coral = 2131099776;
			
			// aapt resource value: 0x7f06003b
			public const int CornflowerBlue = 2131099707;
			
			// aapt resource value: 0x7f06001a
			public const int Cornsilk = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int Cornsilk2 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int Cornsilk3 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int Cornsilk4 = 2131099677;
			
			// aapt resource value: 0x7f06004f
			public const int Cyan = 2131099727;
			
			// aapt resource value: 0x7f06006d
			public const int DarkGoldenrod = 2131099757;
			
			// aapt resource value: 0x7f060054
			public const int DarkGreen = 2131099732;
			
			// aapt resource value: 0x7f060064
			public const int DarkKhaki = 2131099748;
			
			// aapt resource value: 0x7f060055
			public const int DarkOliveGreen = 2131099733;
			
			// aapt resource value: 0x7f06007f
			public const int DarkOrange = 2131099775;
			
			// aapt resource value: 0x7f060091
			public const int DarkOrchid = 2131099793;
			
			// aapt resource value: 0x7f06007b
			public const int DarkSalmon = 2131099771;
			
			// aapt resource value: 0x7f060056
			public const int DarkSeaGreen = 2131099734;
			
			// aapt resource value: 0x7f06003c
			public const int DarkSlateBlue = 2131099708;
			
			// aapt resource value: 0x7f06004c
			public const int DarkTurquoise = 2131099724;
			
			// aapt resource value: 0x7f060092
			public const int DarkViolet = 2131099794;
			
			// aapt resource value: 0x7f060086
			public const int DeepPink = 2131099782;
			
			// aapt resource value: 0x7f060044
			public const int DeepSkyBlue = 2131099716;
			
			// aapt resource value: 0x7f060034
			public const int DimGray = 2131099700;
			
			// aapt resource value: 0x7f060043
			public const int DodgerBlue = 2131099715;
			
			// aapt resource value: 0x7f060079
			public const int Firebrick = 2131099769;
			
			// aapt resource value: 0x7f060007
			public const int FloralWhite = 2131099655;
			
			// aapt resource value: 0x7f060062
			public const int ForestGreen = 2131099746;
			
			// aapt resource value: 0x7f060006
			public const int Gainsboro = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int GhostWhite = 2131099652;
			
			// aapt resource value: 0x7f06006a
			public const int Gold = 2131099754;
			
			// aapt resource value: 0x7f06006c
			public const int Goldenrod = 2131099756;
			
			// aapt resource value: 0x7f060037
			public const int Gray = 2131099703;
			
			// aapt resource value: 0x7f06005f
			public const int GreenYellow = 2131099743;
			
			// aapt resource value: 0x7f060027
			public const int Honeydew = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int Honeydew2 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int Honeydew3 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int Honeydew4 = 2131099690;
			
			// aapt resource value: 0x7f060085
			public const int HotPink = 2131099781;
			
			// aapt resource value: 0x7f06006f
			public const int IndianRed = 2131099759;
			
			// aapt resource value: 0x7f06001e
			public const int Ivory = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int Ivory2 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int Ivory3 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int Ivory4 = 2131099681;
			
			// aapt resource value: 0x7f060065
			public const int Khaki = 2131099749;
			
			// aapt resource value: 0x7f06002e
			public const int Lavender = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int LavenderBlush = 2131099695;
			
			// aapt resource value: 0x7f06005c
			public const int LawnGreen = 2131099740;
			
			// aapt resource value: 0x7f060022
			public const int LemonChiffon = 2131099682;
			
			// aapt resource value: 0x7f060049
			public const int LightBlue = 2131099721;
			
			// aapt resource value: 0x7f060081
			public const int LightCoral = 2131099777;
			
			// aapt resource value: 0x7f060050
			public const int LightCyan = 2131099728;
			
			// aapt resource value: 0x7f06006b
			public const int LightGoldenrod = 2131099755;
			
			// aapt resource value: 0x7f060067
			public const int LightGoldenrodYellow = 2131099751;
			
			// aapt resource value: 0x7f060038
			public const int LightGray = 2131099704;
			
			// aapt resource value: 0x7f060088
			public const int LightPink = 2131099784;
			
			// aapt resource value: 0x7f06007d
			public const int LightSalmon = 2131099773;
			
			// aapt resource value: 0x7f060059
			public const int LightSeaGreen = 2131099737;
			
			// aapt resource value: 0x7f060046
			public const int LightSkyBlue = 2131099718;
			
			// aapt resource value: 0x7f06003f
			public const int LightSlateBlue = 2131099711;
			
			// aapt resource value: 0x7f060036
			public const int LightSlateGray = 2131099702;
			
			// aapt resource value: 0x7f060048
			public const int LightSteelBlue = 2131099720;
			
			// aapt resource value: 0x7f060068
			public const int LightYellow = 2131099752;
			
			// aapt resource value: 0x7f060060
			public const int LimeGreen = 2131099744;
			
			// aapt resource value: 0x7f060009
			public const int Linen = 2131099657;
			
			// aapt resource value: 0x7f06008a
			public const int Maroon = 2131099786;
			
			// aapt resource value: 0x7f060052
			public const int MediumAquamarine = 2131099730;
			
			// aapt resource value: 0x7f060040
			public const int MediumBlue = 2131099712;
			
			// aapt resource value: 0x7f060090
			public const int MediumOrchid = 2131099792;
			
			// aapt resource value: 0x7f060095
			public const int MediumPurple = 2131099797;
			
			// aapt resource value: 0x7f060058
			public const int MediumSeaGreen = 2131099736;
			
			// aapt resource value: 0x7f06003e
			public const int MediumSlateBlue = 2131099710;
			
			// aapt resource value: 0x7f06005e
			public const int MediumSpringGreen = 2131099742;
			
			// aapt resource value: 0x7f06004d
			public const int MediumTurquoise = 2131099725;
			
			// aapt resource value: 0x7f06008b
			public const int MediumVioletRed = 2131099787;
			
			// aapt resource value: 0x7f060039
			public const int MidnightBlue = 2131099705;
			
			// aapt resource value: 0x7f06002b
			public const int MintCream = 2131099691;
			
			// aapt resource value: 0x7f060030
			public const int MistyRose = 2131099696;
			
			// aapt resource value: 0x7f060019
			public const int Moccasin = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int NavajoWhite = 2131099672;
			
			// aapt resource value: 0x7f06003a
			public const int Navy = 2131099706;
			
			// aapt resource value: 0x7f060008
			public const int OldLace = 2131099656;
			
			// aapt resource value: 0x7f060063
			public const int OliveDrab = 2131099747;
			
			// aapt resource value: 0x7f06007e
			public const int Orange = 2131099774;
			
			// aapt resource value: 0x7f060083
			public const int OrangeRed = 2131099779;
			
			// aapt resource value: 0x7f06008f
			public const int Orchid = 2131099791;
			
			// aapt resource value: 0x7f060066
			public const int PaleGoldenrod = 2131099750;
			
			// aapt resource value: 0x7f06005a
			public const int PaleGreen = 2131099738;
			
			// aapt resource value: 0x7f06004b
			public const int PaleTurquoise = 2131099723;
			
			// aapt resource value: 0x7f060089
			public const int PaleVioletRed = 2131099785;
			
			// aapt resource value: 0x7f06000e
			public const int PapayaWhip = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int PeachPuff = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int PeachPuff2 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int PeachPuff3 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int PeachPuff4 = 2131099671;
			
			// aapt resource value: 0x7f060072
			public const int Peru = 2131099762;
			
			// aapt resource value: 0x7f060087
			public const int Pink = 2131099783;
			
			// aapt resource value: 0x7f06008e
			public const int Plum = 2131099790;
			
			// aapt resource value: 0x7f06004a
			public const int PowderBlue = 2131099722;
			
			// aapt resource value: 0x7f060094
			public const int Purple = 2131099796;
			
			// aapt resource value: 0x7f060084
			public const int Red = 2131099780;
			
			// aapt resource value: 0x7f06006e
			public const int RosyBrown = 2131099758;
			
			// aapt resource value: 0x7f060041
			public const int RoyalBlue = 2131099713;
			
			// aapt resource value: 0x7f060070
			public const int SaddleBrown = 2131099760;
			
			// aapt resource value: 0x7f06007c
			public const int Salmon = 2131099772;
			
			// aapt resource value: 0x7f060076
			public const int SandyBrown = 2131099766;
			
			// aapt resource value: 0x7f060057
			public const int SeaGreen = 2131099735;
			
			// aapt resource value: 0x7f060023
			public const int Seashell = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int Seashell2 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int Seashell3 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int Seashell4 = 2131099686;
			
			// aapt resource value: 0x7f060071
			public const int Sienna = 2131099761;
			
			// aapt resource value: 0x7f060045
			public const int SkyBlue = 2131099717;
			
			// aapt resource value: 0x7f06003d
			public const int SlateBlue = 2131099709;
			
			// aapt resource value: 0x7f060035
			public const int SlateGray = 2131099701;
			
			// aapt resource value: 0x7f060000
			public const int Snow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Snow2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Snow3 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Snow4 = 2131099651;
			
			// aapt resource value: 0x7f06005b
			public const int SpringGreen = 2131099739;
			
			// aapt resource value: 0x7f060047
			public const int SteelBlue = 2131099719;
			
			// aapt resource value: 0x7f060077
			public const int Tan = 2131099767;
			
			// aapt resource value: 0x7f060096
			public const int Thistle = 2131099798;
			
			// aapt resource value: 0x7f060082
			public const int Tomato = 2131099778;
			
			// aapt resource value: 0x7f06004e
			public const int Turquoise = 2131099726;
			
			// aapt resource value: 0x7f06008d
			public const int Violet = 2131099789;
			
			// aapt resource value: 0x7f06008c
			public const int VioletRed = 2131099788;
			
			// aapt resource value: 0x7f060075
			public const int Wheat = 2131099765;
			
			// aapt resource value: 0x7f060031
			public const int White = 2131099697;
			
			// aapt resource value: 0x7f060005
			public const int WhiteSmoke = 2131099653;
			
			// aapt resource value: 0x7f060069
			public const int Yellow = 2131099753;
			
			// aapt resource value: 0x7f060061
			public const int YellowGreen = 2131099745;
			
			// aapt resource value: 0x7f060033
			public const int darkslategray = 2131099699;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ala = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int start = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int stop = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int Add = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int Close = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int DatePick = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int Description = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int Done = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int IsAlert = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int TimePick = 2131230731;
			
			// aapt resource value: 0x7f080008
			public const int Title = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int tab1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tab1Content = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int tab2 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int tab2Content = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int tab3 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int tab3Content = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int tabHost = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Save_Update = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int RowDefinition = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int TabsBody = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int TabsHeader = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int TextBox = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int TextView = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Border = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
