#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mini.Resource", IsApplication=true)]

namespace Mini
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07002d
			public const int AliceBlue = 2131165229;
			
			// aapt resource value: 0x7f07000a
			public const int AntiqueWhite = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int AntiqueWhite2 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int AntiqueWhite3 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int AntiqueWhite4 = 2131165197;
			
			// aapt resource value: 0x7f070053
			public const int Aquamarine = 2131165267;
			
			// aapt resource value: 0x7f07002c
			public const int Azure = 2131165228;
			
			// aapt resource value: 0x7f070074
			public const int Beige = 2131165300;
			
			// aapt resource value: 0x7f070010
			public const int Bisque = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Bisque2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int Bisque3 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int Bisque4 = 2131165203;
			
			// aapt resource value: 0x7f070032
			public const int Black = 2131165234;
			
			// aapt resource value: 0x7f07000f
			public const int BlanchedAlmond = 2131165199;
			
			// aapt resource value: 0x7f070042
			public const int Blue = 2131165250;
			
			// aapt resource value: 0x7f070093
			public const int BlueViolet = 2131165331;
			
			// aapt resource value: 0x7f07007a
			public const int Brown = 2131165306;
			
			// aapt resource value: 0x7f070073
			public const int Burlywood = 2131165299;
			
			// aapt resource value: 0x7f070051
			public const int CadetBlue = 2131165265;
			
			// aapt resource value: 0x7f07005d
			public const int Chartreuse = 2131165277;
			
			// aapt resource value: 0x7f070078
			public const int Chocolate = 2131165304;
			
			// aapt resource value: 0x7f070080
			public const int Coral = 2131165312;
			
			// aapt resource value: 0x7f07003b
			public const int CornflowerBlue = 2131165243;
			
			// aapt resource value: 0x7f07001a
			public const int Cornsilk = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int Cornsilk2 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int Cornsilk3 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int Cornsilk4 = 2131165213;
			
			// aapt resource value: 0x7f07004f
			public const int Cyan = 2131165263;
			
			// aapt resource value: 0x7f07006d
			public const int DarkGoldenrod = 2131165293;
			
			// aapt resource value: 0x7f070054
			public const int DarkGreen = 2131165268;
			
			// aapt resource value: 0x7f070064
			public const int DarkKhaki = 2131165284;
			
			// aapt resource value: 0x7f070055
			public const int DarkOliveGreen = 2131165269;
			
			// aapt resource value: 0x7f07007f
			public const int DarkOrange = 2131165311;
			
			// aapt resource value: 0x7f070091
			public const int DarkOrchid = 2131165329;
			
			// aapt resource value: 0x7f07007b
			public const int DarkSalmon = 2131165307;
			
			// aapt resource value: 0x7f070056
			public const int DarkSeaGreen = 2131165270;
			
			// aapt resource value: 0x7f07003c
			public const int DarkSlateBlue = 2131165244;
			
			// aapt resource value: 0x7f07004c
			public const int DarkTurquoise = 2131165260;
			
			// aapt resource value: 0x7f070092
			public const int DarkViolet = 2131165330;
			
			// aapt resource value: 0x7f070086
			public const int DeepPink = 2131165318;
			
			// aapt resource value: 0x7f070044
			public const int DeepSkyBlue = 2131165252;
			
			// aapt resource value: 0x7f070034
			public const int DimGray = 2131165236;
			
			// aapt resource value: 0x7f070043
			public const int DodgerBlue = 2131165251;
			
			// aapt resource value: 0x7f070079
			public const int Firebrick = 2131165305;
			
			// aapt resource value: 0x7f070007
			public const int FloralWhite = 2131165191;
			
			// aapt resource value: 0x7f070062
			public const int ForestGreen = 2131165282;
			
			// aapt resource value: 0x7f070006
			public const int Gainsboro = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int GhostWhite = 2131165188;
			
			// aapt resource value: 0x7f07006a
			public const int Gold = 2131165290;
			
			// aapt resource value: 0x7f07006c
			public const int Goldenrod = 2131165292;
			
			// aapt resource value: 0x7f070037
			public const int Gray = 2131165239;
			
			// aapt resource value: 0x7f07005f
			public const int GreenYellow = 2131165279;
			
			// aapt resource value: 0x7f070027
			public const int Honeydew = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int Honeydew2 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int Honeydew3 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int Honeydew4 = 2131165226;
			
			// aapt resource value: 0x7f070085
			public const int HotPink = 2131165317;
			
			// aapt resource value: 0x7f07006f
			public const int IndianRed = 2131165295;
			
			// aapt resource value: 0x7f07001e
			public const int Ivory = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int Ivory2 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int Ivory3 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int Ivory4 = 2131165217;
			
			// aapt resource value: 0x7f070065
			public const int Khaki = 2131165285;
			
			// aapt resource value: 0x7f07002e
			public const int Lavender = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int LavenderBlush = 2131165231;
			
			// aapt resource value: 0x7f07005c
			public const int LawnGreen = 2131165276;
			
			// aapt resource value: 0x7f070022
			public const int LemonChiffon = 2131165218;
			
			// aapt resource value: 0x7f070049
			public const int LightBlue = 2131165257;
			
			// aapt resource value: 0x7f070081
			public const int LightCoral = 2131165313;
			
			// aapt resource value: 0x7f070050
			public const int LightCyan = 2131165264;
			
			// aapt resource value: 0x7f07006b
			public const int LightGoldenrod = 2131165291;
			
			// aapt resource value: 0x7f070067
			public const int LightGoldenrodYellow = 2131165287;
			
			// aapt resource value: 0x7f070038
			public const int LightGray = 2131165240;
			
			// aapt resource value: 0x7f070088
			public const int LightPink = 2131165320;
			
			// aapt resource value: 0x7f07007d
			public const int LightSalmon = 2131165309;
			
			// aapt resource value: 0x7f070059
			public const int LightSeaGreen = 2131165273;
			
			// aapt resource value: 0x7f070046
			public const int LightSkyBlue = 2131165254;
			
			// aapt resource value: 0x7f07003f
			public const int LightSlateBlue = 2131165247;
			
			// aapt resource value: 0x7f070036
			public const int LightSlateGray = 2131165238;
			
			// aapt resource value: 0x7f070048
			public const int LightSteelBlue = 2131165256;
			
			// aapt resource value: 0x7f070068
			public const int LightYellow = 2131165288;
			
			// aapt resource value: 0x7f070060
			public const int LimeGreen = 2131165280;
			
			// aapt resource value: 0x7f070009
			public const int Linen = 2131165193;
			
			// aapt resource value: 0x7f07008a
			public const int Maroon = 2131165322;
			
			// aapt resource value: 0x7f070052
			public const int MediumAquamarine = 2131165266;
			
			// aapt resource value: 0x7f070040
			public const int MediumBlue = 2131165248;
			
			// aapt resource value: 0x7f070090
			public const int MediumOrchid = 2131165328;
			
			// aapt resource value: 0x7f070095
			public const int MediumPurple = 2131165333;
			
			// aapt resource value: 0x7f070058
			public const int MediumSeaGreen = 2131165272;
			
			// aapt resource value: 0x7f07003e
			public const int MediumSlateBlue = 2131165246;
			
			// aapt resource value: 0x7f07005e
			public const int MediumSpringGreen = 2131165278;
			
			// aapt resource value: 0x7f07004d
			public const int MediumTurquoise = 2131165261;
			
			// aapt resource value: 0x7f07008b
			public const int MediumVioletRed = 2131165323;
			
			// aapt resource value: 0x7f070039
			public const int MidnightBlue = 2131165241;
			
			// aapt resource value: 0x7f07002b
			public const int MintCream = 2131165227;
			
			// aapt resource value: 0x7f070030
			public const int MistyRose = 2131165232;
			
			// aapt resource value: 0x7f070019
			public const int Moccasin = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int NavajoWhite = 2131165208;
			
			// aapt resource value: 0x7f07003a
			public const int Navy = 2131165242;
			
			// aapt resource value: 0x7f070008
			public const int OldLace = 2131165192;
			
			// aapt resource value: 0x7f070063
			public const int OliveDrab = 2131165283;
			
			// aapt resource value: 0x7f07007e
			public const int Orange = 2131165310;
			
			// aapt resource value: 0x7f070083
			public const int OrangeRed = 2131165315;
			
			// aapt resource value: 0x7f07008f
			public const int Orchid = 2131165327;
			
			// aapt resource value: 0x7f070066
			public const int PaleGoldenrod = 2131165286;
			
			// aapt resource value: 0x7f07005a
			public const int PaleGreen = 2131165274;
			
			// aapt resource value: 0x7f07004b
			public const int PaleTurquoise = 2131165259;
			
			// aapt resource value: 0x7f070089
			public const int PaleVioletRed = 2131165321;
			
			// aapt resource value: 0x7f07000e
			public const int PapayaWhip = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int PeachPuff = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int PeachPuff2 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int PeachPuff3 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int PeachPuff4 = 2131165207;
			
			// aapt resource value: 0x7f070072
			public const int Peru = 2131165298;
			
			// aapt resource value: 0x7f070087
			public const int Pink = 2131165319;
			
			// aapt resource value: 0x7f07008e
			public const int Plum = 2131165326;
			
			// aapt resource value: 0x7f07004a
			public const int PowderBlue = 2131165258;
			
			// aapt resource value: 0x7f070094
			public const int Purple = 2131165332;
			
			// aapt resource value: 0x7f070084
			public const int Red = 2131165316;
			
			// aapt resource value: 0x7f07006e
			public const int RosyBrown = 2131165294;
			
			// aapt resource value: 0x7f070041
			public const int RoyalBlue = 2131165249;
			
			// aapt resource value: 0x7f070070
			public const int SaddleBrown = 2131165296;
			
			// aapt resource value: 0x7f07007c
			public const int Salmon = 2131165308;
			
			// aapt resource value: 0x7f070076
			public const int SandyBrown = 2131165302;
			
			// aapt resource value: 0x7f070057
			public const int SeaGreen = 2131165271;
			
			// aapt resource value: 0x7f070023
			public const int Seashell = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int Seashell2 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int Seashell3 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int Seashell4 = 2131165222;
			
			// aapt resource value: 0x7f070071
			public const int Sienna = 2131165297;
			
			// aapt resource value: 0x7f070045
			public const int SkyBlue = 2131165253;
			
			// aapt resource value: 0x7f07003d
			public const int SlateBlue = 2131165245;
			
			// aapt resource value: 0x7f070035
			public const int SlateGray = 2131165237;
			
			// aapt resource value: 0x7f070000
			public const int Snow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Snow2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Snow3 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Snow4 = 2131165187;
			
			// aapt resource value: 0x7f07005b
			public const int SpringGreen = 2131165275;
			
			// aapt resource value: 0x7f070047
			public const int SteelBlue = 2131165255;
			
			// aapt resource value: 0x7f070077
			public const int Tan = 2131165303;
			
			// aapt resource value: 0x7f070096
			public const int Thistle = 2131165334;
			
			// aapt resource value: 0x7f070082
			public const int Tomato = 2131165314;
			
			// aapt resource value: 0x7f07004e
			public const int Turquoise = 2131165262;
			
			// aapt resource value: 0x7f07008d
			public const int Violet = 2131165325;
			
			// aapt resource value: 0x7f07008c
			public const int VioletRed = 2131165324;
			
			// aapt resource value: 0x7f070075
			public const int Wheat = 2131165301;
			
			// aapt resource value: 0x7f070031
			public const int White = 2131165233;
			
			// aapt resource value: 0x7f070005
			public const int WhiteSmoke = 2131165189;
			
			// aapt resource value: 0x7f070069
			public const int Yellow = 2131165289;
			
			// aapt resource value: 0x7f070061
			public const int YellowGreen = 2131165281;
			
			// aapt resource value: 0x7f070033
			public const int darkslategray = 2131165235;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080015
			public const int A = 2131230741;
			
			// aapt resource value: 0x7f080013
			public const int AND = 2131230739;
			
			// aapt resource value: 0x7f08004f
			public const int APSolve = 2131230799;
			
			// aapt resource value: 0x7f08004e
			public const int APSpinner = 2131230798;
			
			// aapt resource value: 0x7f080020
			public const int APolar = 2131230752;
			
			// aapt resource value: 0x7f08000b
			public const int AText = 2131230731;
			
			// aapt resource value: 0x7f080023
			public const int Abs = 2131230755;
			
			// aapt resource value: 0x7f08003e
			public const int Add = 2131230782;
			
			// aapt resource value: 0x7f080030
			public const int Angle = 2131230768;
			
			// aapt resource value: 0x7f08004d
			public const int AnsAp = 2131230797;
			
			// aapt resource value: 0x7f080053
			public const int AnsGp = 2131230803;
			
			// aapt resource value: 0x7f080059
			public const int AnsHp = 2131230809;
			
			// aapt resource value: 0x7f080071
			public const int AnsThreeX = 2131230833;
			
			// aapt resource value: 0x7f080072
			public const int AnsThreeY = 2131230834;
			
			// aapt resource value: 0x7f080073
			public const int AnsThreeZ = 2131230835;
			
			// aapt resource value: 0x7f080062
			public const int AnsTwoX = 2131230818;
			
			// aapt resource value: 0x7f080063
			public const int AnsTwoY = 2131230819;
			
			// aapt resource value: 0x7f080001
			public const int AtoF = 2131230721;
			
			// aapt resource value: 0x7f080016
			public const int B = 2131230742;
			
			// aapt resource value: 0x7f080007
			public const int BackFromList = 2131230727;
			
			// aapt resource value: 0x7f080046
			public const int BackFromOthers = 2131230790;
			
			// aapt resource value: 0x7f08000c
			public const int BackSpace = 2131230732;
			
			// aapt resource value: 0x7f080017
			public const int C = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int CBRT = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int Clr = 2131230738;
			
			// aapt resource value: 0x7f080032
			public const int Comma = 2131230770;
			
			// aapt resource value: 0x7f080048
			public const int ConstantSpinner = 2131230792;
			
			// aapt resource value: 0x7f080075
			public const int ConvSpinner = 2131230837;
			
			// aapt resource value: 0x7f080076
			public const int Conv_From = 2131230838;
			
			// aapt resource value: 0x7f080078
			public const int Conv_To = 2131230840;
			
			// aapt resource value: 0x7f080025
			public const int Cos = 2131230757;
			
			// aapt resource value: 0x7f080028
			public const int Cosh = 2131230760;
			
			// aapt resource value: 0x7f080044
			public const int Decimal = 2131230788;
			
			// aapt resource value: 0x7f08000f
			public const int Degree = 2131230735;
			
			// aapt resource value: 0x7f08004b
			public const int Diff_AP = 2131230795;
			
			// aapt resource value: 0x7f080057
			public const int Diff_HP = 2131230807;
			
			// aapt resource value: 0x7f08000e
			public const int Down = 2131230734;
			
			// aapt resource value: 0x7f080035
			public const int Eight = 2131230773;
			
			// aapt resource value: 0x7f08004a
			public const int First_AP = 2131230794;
			
			// aapt resource value: 0x7f080050
			public const int First_GP = 2131230800;
			
			// aapt resource value: 0x7f080056
			public const int First_HP = 2131230806;
			
			// aapt resource value: 0x7f08003b
			public const int Five = 2131230779;
			
			// aapt resource value: 0x7f08003a
			public const int Four = 2131230778;
			
			// aapt resource value: 0x7f080077
			public const int FromSpinner = 2131230839;
			
			// aapt resource value: 0x7f080055
			public const int GPSolve = 2131230805;
			
			// aapt resource value: 0x7f080054
			public const int GPSpinner = 2131230804;
			
			// aapt resource value: 0x7f080011
			public const int Gradient = 2131230737;
			
			// aapt resource value: 0x7f08005b
			public const int HPSolve = 2131230811;
			
			// aapt resource value: 0x7f08005a
			public const int HPSpinner = 2131230810;
			
			// aapt resource value: 0x7f080018
			public const int Inv = 2131230744;
			
			// aapt resource value: 0x7f080002
			public const int IsMat = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int IsStat = 2131230725;
			
			// aapt resource value: 0x7f080022
			public const int LCM = 2131230754;
			
			// aapt resource value: 0x7f08001d
			public const int LN = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int LOG = 2131230748;
			
			// aapt resource value: 0x7f08004c
			public const int Last_AP = 2131230796;
			
			// aapt resource value: 0x7f080052
			public const int Last_GP = 2131230802;
			
			// aapt resource value: 0x7f080058
			public const int Last_HP = 2131230808;
			
			// aapt resource value: 0x7f080009
			public const int ListItemsGrid = 2131230729;
			
			// aapt resource value: 0x7f08002f
			public const int ListOfPrime = 2131230767;
			
			// aapt resource value: 0x7f08002a
			public const int Mat = 2131230762;
			
			// aapt resource value: 0x7f080003
			public const int MatrixM = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MatrixN = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int MatrixOrStatSpinner = 2131230720;
			
			// aapt resource value: 0x7f08003d
			public const int Minus = 2131230781;
			
			// aapt resource value: 0x7f08001b
			public const int NRT = 2131230747;
			
			// aapt resource value: 0x7f080008
			public const int NextFromList = 2131230728;
			
			// aapt resource value: 0x7f080036
			public const int Nine = 2131230774;
			
			// aapt resource value: 0x7f080040
			public const int One = 2131230784;
			
			// aapt resource value: 0x7f08002d
			public const int Others = 2131230765;
			
			// aapt resource value: 0x7f080033
			public const int Percent = 2131230771;
			
			// aapt resource value: 0x7f08001e
			public const int Permutation = 2131230750;
			
			// aapt resource value: 0x7f080031
			public const int Pi = 2131230769;
			
			// aapt resource value: 0x7f08002e
			public const int Prime = 2131230766;
			
			// aapt resource value: 0x7f08000a
			public const int QText = 2131230730;
			
			// aapt resource value: 0x7f080047
			public const int Q_Constant = 2131230791;
			
			// aapt resource value: 0x7f08001f
			public const int RAngle = 2131230751;
			
			// aapt resource value: 0x7f080010
			public const int Radient = 2131230736;
			
			// aapt resource value: 0x7f080051
			public const int Rat_GP = 2131230801;
			
			// aapt resource value: 0x7f08002b
			public const int SD = 2131230763;
			
			// aapt resource value: 0x7f080019
			public const int SQRT = 2131230745;
			
			// aapt resource value: 0x7f080034
			public const int Seven = 2131230772;
			
			// aapt resource value: 0x7f080024
			public const int Sin = 2131230756;
			
			// aapt resource value: 0x7f080027
			public const int Sinh = 2131230759;
			
			// aapt resource value: 0x7f08003c
			public const int Six = 2131230780;
			
			// aapt resource value: 0x7f080045
			public const int Solve = 2131230789;
			
			// aapt resource value: 0x7f080006
			public const int StatCount = 2131230726;
			
			// aapt resource value: 0x7f080039
			public const int Sum = 2131230777;
			
			// aapt resource value: 0x7f08003f
			public const int SumOfSquare = 2131230783;
			
			// aapt resource value: 0x7f080026
			public const int Tan = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int Tanh = 2131230761;
			
			// aapt resource value: 0x7f080042
			public const int Three = 2131230786;
			
			// aapt resource value: 0x7f080068
			public const int ThreeA = 2131230824;
			
			// aapt resource value: 0x7f080065
			public const int ThreeA1 = 2131230821;
			
			// aapt resource value: 0x7f080066
			public const int ThreeA2 = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int ThreeA3 = 2131230823;
			
			// aapt resource value: 0x7f08006c
			public const int ThreeB = 2131230828;
			
			// aapt resource value: 0x7f080069
			public const int ThreeB1 = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public const int ThreeB2 = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public const int ThreeB3 = 2131230827;
			
			// aapt resource value: 0x7f080070
			public const int ThreeC = 2131230832;
			
			// aapt resource value: 0x7f08006d
			public const int ThreeC1 = 2131230829;
			
			// aapt resource value: 0x7f08006e
			public const int ThreeC2 = 2131230830;
			
			// aapt resource value: 0x7f08006f
			public const int ThreeC3 = 2131230831;
			
			// aapt resource value: 0x7f080074
			public const int ThreeSolve = 2131230836;
			
			// aapt resource value: 0x7f080049
			public const int ToConstant = 2131230793;
			
			// aapt resource value: 0x7f080079
			public const int ToSpinner = 2131230841;
			
			// aapt resource value: 0x7f080041
			public const int Two = 2131230785;
			
			// aapt resource value: 0x7f08005e
			public const int TwoA = 2131230814;
			
			// aapt resource value: 0x7f08005c
			public const int TwoA1 = 2131230812;
			
			// aapt resource value: 0x7f08005d
			public const int TwoA2 = 2131230813;
			
			// aapt resource value: 0x7f080061
			public const int TwoB = 2131230817;
			
			// aapt resource value: 0x7f08005f
			public const int TwoB1 = 2131230815;
			
			// aapt resource value: 0x7f080060
			public const int TwoB2 = 2131230816;
			
			// aapt resource value: 0x7f080064
			public const int TwoSolve = 2131230820;
			
			// aapt resource value: 0x7f08000d
			public const int Up = 2131230733;
			
			// aapt resource value: 0x7f08002c
			public const int Var = 2131230764;
			
			// aapt resource value: 0x7f080037
			public const int XBar = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int XBarSqr = 2131230776;
			
			// aapt resource value: 0x7f080014
			public const int XOR = 2131230740;
			
			// aapt resource value: 0x7f080043
			public const int Zero = 2131230787;
			
			// aapt resource value: 0x7f080021
			public const int i = 2131230753;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int List = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItems = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Others = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050013
			public const int Mono_Android_Theme_Splash = 2131034131;
			
			// aapt resource value: 0x7f050002
			public const int SpinnerDropDownItem = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int SpinnerItem = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int buttons = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int customtheme = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int dropDown = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int header = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int layout = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int layoutButton = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int layoutColumn = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int layoutRow = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int layoutTextbox = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int others = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int othersTextBox = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int othersTextView = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int radioButton = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int radioButtonGroup = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textView = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int textbox = 2131034124;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Gradient = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
